language: python
python:
  - "2.7"


install:

    # command to install dependencies
    - sudo pip install flake8
    - pip install --process-dependency-links .

script:

    # command to run tests
    - flake8 .
