keystone:
    username: <user>
    password: <pass>
    tenant_name: <tenant>
    auth_url: http://192.168.9.70:5000/v2.0/

networking:
    neutron_supported_region: true
    neutron_url: http://192.168.9.70:9696/
    int_network:
        use_existing: false
        name: cloudify-admin-network
    subnet:
        use_existing: false
        name: cloudify-admin-network-subnet
        ip_version: 4
        cidr: 10.67.79.0/24
        dns_nameservers: ['192.168.10.11', '192.168.10.15']
    ext_network:
        use_existing: true
        name: public
    router:
        use_existing: false
        name: cloudify-router
    agents_security_group:
        use_existing: false
        name: cloudify-sg-agents
    management_security_group:
        use_existing: false
        name: cloudify-sg-management
        cidr: 0.0.0.0/0

compute:
    region: ''
    management_server:
        #floating_ip: [FLOATING_IP] #uncomment and provide preallocated ip to disable auto-allocation of new IP on each run
        user_on_management: ubuntu
        userhome_on_management: /home/ubuntu
        instance:
            use_existing: false
            name: cloudify-management-server
            image: 69078a66-a474-4e0a-afb0-7c0c339d5d20
            flavor: 3
        management_keypair:
            use_existing: false
            name: cloudify-management-kp
            auto_generated:
                private_key_target_path: ~/.ssh/cloudify-management-kp.pem
    agent_servers:
        agents_keypair:
            use_existing: false
            name: cloudify-agents-kp
            auto_generated:
                private_key_target_path: ~/.ssh/cloudify-agents-kp.pem

cloudify:
   cloudify_branch: develop
